### ISSUE TITLE
大佬，横向cardViewPager可以做吗

### ISSUE THREAD

**Issue by wangrui112211** [Origogi/Flutter_Vertical_ViewPager#1]
大佬，横向cardViewPager可以做吗

**Comment by Origogi** [comment]
@wangrui112211 

Yes :) 

used below plugin~

https://github.com/Origogi/Horizontal_Card_Pager

**Comment by wangrui112211** [comment]
很少能见到这么认真回复的大佬，May I get to Know you？Where are you come from?
I work in BeiJing China.I'v being android engineer for five years, But I'm
not that big dream to be very great. I just like it.
In addition, I may return to Xi'an China in the next two years. Because My
husband's hometown is there. And Xi'an has a big grow that I can work here.

Jeongtae Kim ***@***.***> 于2021年4月12日周一 下午12:47写道：

**Comment by wangrui112211** [comment]
我自己做的不流畅，横屏可以做成长方形的吗？🙏

Jeongtae Kim ***@***.***> 于2021年4月12日周一 下午12:47写道：

**Comment by wangrui112211** [comment]
[image: image.png]

王瑞 ***@***.***> 于2021年4月16日周五 上午10:37写道：

**Comment by wangrui112211** [comment]
> @wangrui112211
> 
> Yes :)
> 
> used below plugin~
> 
> https://github.com/Origogi/Horizontal_Card_Pager

Thank You!
